[package]
name = "app"
version = "2.0.0"
description = "A Casual Design & Shoot Game with Tauri + PixiJS"
authors = ["AR10"]
license = "MIT"
default-run = "app"
edition = "2021"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
tauri = { version = "2.10.3", features = [] }
tauri-plugin-devtools = "2.1.0"
chrono = { version = "0.4", features = ["serde"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[profile.dev]
incremental = true

[profile.release]
strip = true
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
